eval:
  actual_path: "data/processed/energy_features.csv"

  test_pred_path: "data/processed/test_predictions.csv"
  future_pred_path: "data/processed/future_predictions.csv"

  target_col: "PJME_MW"
  pred_col: "prediction"
  datetime_col: "Datetime"

  output_dir: "data/evaluation"
